#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=6

# Состояние между запусками — чтобы повторный прогон не переспрашивал всё.
# Секретов здесь нет и быть не должно: ключ service account живёт только в
# скачанном JSON и на сервере, а сюда не пишется ни при каких условиях.
ENV_FILE="${ENV_FILE:-$HOME/.qmedia-registry-wizard.env}"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

# Корень форка — от расположения самого скрипта, а не от того, откуда его звали.
FORK_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Ни id таблицы, ни адрес её владельца здесь не зашиты: репозиторий публичный.
# Спрашиваем их у того, кто запускает, — см. qmedia-ads-agent/docs/adr/0008.

banner "Реестр Аккаунтов — доступ для сервера"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — включить Sheets API"
say "Нужен тот же проект, где живут OAuth-клиент и developer token Google Ads."
ask GCP_PROJECT_ID "ID проекта в Google Cloud:"
if [[ -z "$GCP_PROJECT_ID" ]]; then
  warn "без ID проекта дальше нельзя"; exit 1
fi
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
open_url "https://console.cloud.google.com/apis/library/sheets.googleapis.com?project=${GCP_PROJECT_ID}"
step "Нажмите Enable. Если написано Manage — API уже включён, это нормально."
note "Без этого шага чтение таблицы отобьётся с 403, а причина в тексте ошибки не видна."
pause "Готово?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — создать service account"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create?project=${GCP_PROJECT_ID}"
step "Имя: registry-reader (или любое понятное). Нажмите Create and continue."
step "Роли в проекте НЕ выдавайте — пропустите этот шаг и нажмите Done."
note "Доступ к Реестру даёт шаринг самого файла, а не роль в проекте."
note "Робот с ролью в проекте получил бы права, которые ему не нужны."
ask REGISTRY_SA_EMAIL "Адрес созданного робота (…@…iam.gserviceaccount.com):"
if [[ "$REGISTRY_SA_EMAIL" != *"@"*".iam.gserviceaccount.com" ]]; then
  warn "не похоже на адрес service account — проверьте и запустите визард заново"; exit 1
fi
write_env REGISTRY_SA_EMAIL "$REGISTRY_SA_EMAIL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — скачать JSON-ключ"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts?project=${GCP_PROJECT_ID}"
step "Откройте робота ${REGISTRY_SA_EMAIL} → вкладка Keys."
step "Add key → Create new key → тип JSON → Create. Файл скачается сам."
warn "Если кнопки Create new key нет — политика организации запрещает ключи."
note "Тогда это решается отдельно (Workload Identity), и визард здесь не поможет."
ask SA_KEY_PATH "Путь к скачанному JSON (например ~/Downloads/proj-abc123.json):"
SA_KEY_PATH="${SA_KEY_PATH/#\~/$HOME}"
if [[ ! -f "$SA_KEY_PATH" ]]; then
  warn "файла нет: $SA_KEY_PATH"; exit 1
fi
if ! grep -q '"client_email"' "$SA_KEY_PATH"; then
  warn "это не похоже на ключ service account — нет поля client_email"; exit 1
fi
if ! grep -q "$REGISTRY_SA_EMAIL" "$SA_KEY_PATH"; then
  warn "ключ выписан на другого робота, не на $REGISTRY_SA_EMAIL"
  confirm "Всё равно продолжить?" || exit 1
fi
write_env SA_KEY_PATH "$SA_KEY_PATH"
SA_KEY_B64="$(base64 < "$SA_KEY_PATH" | tr -d '\n')"
say "Ключ прочитан. На экран он не выводится и в состояние визарда не пишется."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Таблица — выдать роботу доступ на чтение"
say "Нужен id таблицы Реестра — часть её URL между /d/ и /edit."
ask REGISTRY_SHEET_ID "ID таблицы:"
if [[ -z "$REGISTRY_SHEET_ID" ]]; then
  warn "без id таблицы дальше нельзя"; exit 1
fi
write_env REGISTRY_SHEET_ID "$REGISTRY_SHEET_ID"
open_url "https://docs.google.com/spreadsheets/d/${REGISTRY_SHEET_ID}/edit"
step "Попросите ВЛАДЕЛЬЦА таблицы открыть «Настройки доступа» и добавить:"
say ""
say "      ${BOLD}${REGISTRY_SA_EMAIL}${RESET}"
say ""
step "Роль — «Читатель» (Viewer). Галочку «Уведомить» лучше снять: робот почту не читает."
warn "Именно адресный доступ, а НЕ «доступ по ссылке»."
note "Ссылка сделала бы таблицу доступной каждому, у кого есть URL."
pause "Доступ выдан?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Проверка — прочитать Реестр этим ключом"
PY_BIN="$FORK_REPO/.venv/bin/python"
if [[ ! -x "$PY_BIN" ]]; then
  warn "нет локального venv форка: $PY_BIN"
  note "Соберите его по FORK.md, раздел «Локальная разработка», и запустите визард заново:"
  note "  cd $FORK_REPO && python3.13 -m venv .venv && .venv/bin/pip install -e ."
  exit 1
fi

registry_check() {
  ( export GOOGLE_ADS_REGISTRY_SHEET_ID="$REGISTRY_SHEET_ID"
    export GOOGLE_ADS_REGISTRY_SA_KEY="$SA_KEY_B64"
    "$PY_BIN" - <<'PYEOF'
import sys
from ads_mcp.registry import RegistryUnavailable, fetch
try:
    snapshot = fetch()
except RegistryUnavailable as error:
    print(f"ОТКАЗ: {error}")
    sys.exit(1)
print(f"Клиентов: {len(snapshot.clients)}")
print(f"customer_id в allowlist: {len(snapshot.allowed_customer_ids())}")
print(f"Проблем в Реестре: {len(snapshot.problems)}")
for problem in snapshot.problems[:10]:
    print(f"  - {problem}")
PYEOF
  )
}

while true; do
  say "Читаю таблицу тем же кодом, что будет работать на сервере…"
  say ""
  if registry_check; then
    say ""
    printf '  %s✓ Реестр читается%s\n' "$GREEN" "$RESET"
    break
  fi
  say ""
  warn "прочитать не удалось"
  note "403 — не выдан доступ роботу или не включён Sheets API (шаги 1 и 4)."
  note "404 — не тот id таблицы."
  note "No header row — в таблице переименовали колонки."
  confirm "Исправили и хотите повторить?" || { warn "останавливаюсь, сервер не тронут"; exit 1; }
done
pause "Идём к серверу?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Сервер — прописать Реестр в .env"
say "Правим ${BOLD}боевой${RESET} .env. Старая переменная allowlist удаляется, Реестр её заменяет."
ask DEPLOY_HOST "Хост сервера (DEPLOYMENT_HOST):"
ask DEPLOY_USER "Пользователь (DEPLOYMENT_USER):"
ask DEPLOY_FOLDER "Каталог деплоя (DEPLOYMENT_FOLDER, где лежит .env):"
if [[ -z "$DEPLOY_HOST" || -z "$DEPLOY_USER" || -z "$DEPLOY_FOLDER" ]]; then
  warn "не хватает данных для SSH"; exit 1
fi
write_env DEPLOY_HOST "$DEPLOY_HOST"
write_env DEPLOY_USER "$DEPLOY_USER"
write_env DEPLOY_FOLDER "$DEPLOY_FOLDER"

SSH_TARGET="$DEPLOY_USER@$DEPLOY_HOST"
printf -v Q_FOLDER '%q' "$DEPLOY_FOLDER"

say ""
say "Будет сделано в ${DEPLOY_FOLDER}/.env:"
say "  ${RED}− GOOGLE_ADS_ALLOWED_CUSTOMER_IDS=…${RESET}"
say "  ${GREEN}+ GOOGLE_ADS_REGISTRY_SHEET_ID=${REGISTRY_SHEET_ID}${RESET}"
say "  ${GREEN}+ GOOGLE_ADS_REGISTRY_SA_KEY=…${RESET}  (ключ, на экран не выводится)"
say ""
note "Копия текущего .env останется рядом как .env.bak.<timestamp>."
confirm "Выполнить?" || { warn "ничего не изменено"; exit 1; }

if ! ssh "$SSH_TARGET" "set -e; f=$Q_FOLDER/.env; test -f \"\$f\"; cp \"\$f\" \"\$f.bak.\$(date +%s)\"; t=\$(mktemp); grep -vE '^(GOOGLE_ADS_ALLOWED_CUSTOMER_IDS|GOOGLE_ADS_REGISTRY_SHEET_ID|GOOGLE_ADS_REGISTRY_SA_KEY)=' \"\$f\" > \"\$t\"; mv \"\$t\" \"\$f\"; chmod 600 \"\$f\""; then
  warn "не удалось подготовить .env на сервере — ничего не дописано"; exit 1
fi

if ! { printf 'GOOGLE_ADS_REGISTRY_SHEET_ID=%s\n' "$REGISTRY_SHEET_ID"
       printf 'GOOGLE_ADS_REGISTRY_SA_KEY=%s\n' "$SA_KEY_B64"
     } | ssh "$SSH_TARGET" "cat >> $Q_FOLDER/.env"; then
  warn "не удалось дописать переменные — восстановите .env из .env.bak.*"; exit 1
fi

say ""
say "Проверяю то, что проверит preflight деплоя:"
ssh "$SSH_TARGET" "cd $Q_FOLDER; for v in GOOGLE_ADS_REGISTRY_SHEET_ID GOOGLE_ADS_REGISTRY_SA_KEY; do
  if grep -q \"^\${v}=.\" .env; then echo \"  OK   \$v — задана и непуста\"; else echo \"  ПУСТО \$v\"; fi; done
  if grep -q '^GOOGLE_ADS_ALLOWED_CUSTOMER_IDS=' .env; then echo '  ОСТАЛАСЬ GOOGLE_ADS_ALLOWED_CUSTOMER_IDS'; else echo '  OK   GOOGLE_ADS_ALLOWED_CUSTOMER_IDS удалена'; fi
  if grep -q CHANGE_ME .env; then echo '  ВНИМАНИЕ: в .env остались плейсхолдеры CHANGE_ME'; fi"

finish

printf '  %sЧто дальше — руками, по одному:%s\n\n' "$BOLD" "$RESET"
note "1. Смержить и запушить ветку Реестра в этом форке."
note "   Пуш в dev запускает боевой деплой — делайте это, глядя на зелёный CI."
note "2. Проверить на реальном Клиенте: registry_find_client находит,"
note "   search по его Аккаунту проходит, по чужому — отбивается."
note "3. Только после этого мержить ветку Реестра в qmedia-ads-agent."
note "   Обратный порядок оставит Менеджеров без Реестра совсем."
printf '\n'
